// server/src/staffControlls/adminActivityController.js
import { prisma } from "../config/db.js";
import cacheService from "../utils/cacheService.js";

const schoolGuard = (req) => {
  const schoolId = req.user?.schoolId;
  if (!schoolId) throw new Error("No schoolId on token");
  return schoolId;
};

const ok  = (res, data, status = 200) => res.status(status).json({ success: true,  ...data });
const err = (res, msg, status = 400)  => res.status(status).json({ success: false, message: msg });

// ═══════════════════════════════════════════════════════════════
//  ACTIVITIES
// ═══════════════════════════════════════════════════════════════

export async function getActivities(req, res) {
  try {
    const schoolId = schoolGuard(req);
    const { academicYearId, participationType, category } = req.query;

    const cacheKey = await cacheService.buildKey(
      schoolId,
      `activities:list:${academicYearId || "all"}:${participationType || "all"}:${category || "all"}`
    );
    const cached = await cacheService.get(cacheKey);
    if (cached) return ok(res, { data: JSON.parse(cached) });

    const activities = await prisma.activity.findMany({
      where: {
        schoolId,
        isArchived: false,
        ...(academicYearId    ? { academicYearId }    : {}),
        ...(participationType ? { participationType } : {}),
        ...(category          ? { category }          : {}),
      },
      include: {
        academicYear:    { select: { id: true, name: true, isActive: true } },
        activityClasses: {
          include: {
            classSection: { select: { id: true, grade: true, section: true, name: true } },
          },
        },
        _count: {
          select: {
            enrollments: { where: { status: "ACTIVE" } },
            events:      { where: { isAutoGenerated: false } },
          },
        },
      },
      orderBy: { createdAt: "desc" },
    });

    await cacheService.set(cacheKey, activities);
    return ok(res, { data: activities });
  } catch (e) {
    console.error("[getActivities]", e);
    return err(res, e.message, 500);
  }
}

export async function getActivityById(req, res) {
  try {
    const schoolId = schoolGuard(req);

    const cacheKey = await cacheService.buildKey(schoolId, `activities:${req.params.id}`);
    const cached = await cacheService.get(cacheKey);
    if (cached) return ok(res, { data: JSON.parse(cached) });

    const activity = await prisma.activity.findFirst({
      where: { id: req.params.id, schoolId, isArchived: false },
      include: {
        academicYear:    { select: { id: true, name: true } },
        activityClasses: {
          include: {
            classSection: { select: { id: true, grade: true, section: true, name: true } },
          },
        },
        enrollments: {
          where:   { status: "ACTIVE" },
          include: { student: { select: { id: true, name: true, email: true } } },
        },
        events: {
          where:  { isAutoGenerated: false, isArchived: false },
          select: { id: true, name: true, eventType: true, eventDate: true, status: true, participationMode: true },
        },
        _count: {
          select: {
            enrollments: { where: { status: "ACTIVE" } },
            events:      { where: { isAutoGenerated: false, isArchived: false } },
          },
        },
      },
    });

    if (!activity) return err(res, "Activity not found", 404);
    await cacheService.set(cacheKey, activity);
    return ok(res, { data: activity });
  } catch (e) {
    console.error("[getActivityById]", e);
    return err(res, e.message, 500);
  }
}

export async function createActivity(req, res) {
  try {
    const schoolId    = schoolGuard(req);
    const createdById = req.user.id;
    const { name, description, category, participationType, academicYearId, classSectionIds = [] } = req.body;

    if (!name)              return err(res, "name is required");
    if (!category)          return err(res, "category is required (SPORTS, CULTURAL, ACADEMIC, OTHER)");
    if (!participationType) return err(res, "participationType is required (INDIVIDUAL, TEAM)");
    if (!academicYearId)    return err(res, "academicYearId is required");

    const validCategories    = ["SPORTS", "CULTURAL", "ACADEMIC", "OTHER"];
    const validParticipation = ["INDIVIDUAL", "TEAM"];
    if (!validCategories.includes(category))             return err(res, `category must be one of ${validCategories.join(", ")}`);
    if (!validParticipation.includes(participationType)) return err(res, `participationType must be one of ${validParticipation.join(", ")}`);

    const ay = await prisma.academicYear.findFirst({ where: { id: academicYearId, schoolId } });
    if (!ay) return err(res, "Academic year not found");

    const activity = await prisma.activity.create({
      data: {
        name, description, category, participationType, schoolId, academicYearId, createdById,
        activityClasses: { create: classSectionIds.map((csId) => ({ classSectionId: csId })) },
      },
      include: {
        academicYear:    { select: { id: true, name: true } },
        activityClasses: {
          include: { classSection: { select: { id: true, grade: true, section: true, name: true } } },
        },
      },
    });

    await cacheService.invalidateSchool(schoolId);
    return ok(res, { data: activity }, 201);
  } catch (e) {
    console.error("[createActivity]", e);
    return err(res, e.message, 500);
  }
}

export async function updateActivity(req, res) {
  try {
    const schoolId = schoolGuard(req);
    const existing = await prisma.activity.findFirst({ where: { id: req.params.id, schoolId, isArchived: false } });
    if (!existing) return err(res, "Activity not found", 404);

    const { name, description, category, participationType, classSectionIds } = req.body;

    const activity = await prisma.$transaction(async (tx) => {
      if (Array.isArray(classSectionIds)) {
        await tx.activityClass.deleteMany({ where: { activityId: req.params.id } });
        await tx.activityClass.createMany({
          data: classSectionIds.map((csId) => ({ activityId: req.params.id, classSectionId: csId })),
        });
      }
      return tx.activity.update({
        where: { id: req.params.id },
        data: {
          ...(name              !== undefined ? { name }              : {}),
          ...(description       !== undefined ? { description }       : {}),
          ...(category          !== undefined ? { category }          : {}),
          ...(participationType !== undefined ? { participationType } : {}),
        },
        include: {
          academicYear:    { select: { id: true, name: true } },
          activityClasses: {
            include: { classSection: { select: { id: true, grade: true, section: true, name: true } } },
          },
        },
      });
    });

    await cacheService.invalidateSchool(schoolId);
    return ok(res, { data: activity });
  } catch (e) {
    console.error("[updateActivity]", e);
    return err(res, e.message, 500);
  }
}

export async function deleteActivity(req, res) {
  try {
    const schoolId = schoolGuard(req);
    const existing = await prisma.activity.findFirst({ where: { id: req.params.id, schoolId, isArchived: false } });
    if (!existing) return err(res, "Activity not found", 404);

    const activeEnrollments = await prisma.studentActivityEnrollment.count({
      where: { activityId: req.params.id, status: "ACTIVE" },
    });
    if (activeEnrollments > 0) {
      return err(res, `Cannot archive: ${activeEnrollments} active student(s) enrolled. Remove members first.`, 409);
    }

    await prisma.$transaction([
      prisma.activityEvent.updateMany({
        where: { activityId: req.params.id, isAutoGenerated: true },
        data:  { isArchived: true },
      }),
      prisma.activity.update({
        where: { id: req.params.id },
        data:  { isArchived: true },
      }),
    ]);

    await cacheService.invalidateSchool(schoolId);
    return ok(res, { message: "Activity archived successfully" });
  } catch (e) {
    console.error("[deleteActivity]", e);
    return err(res, e.message, 500);
  }
}

// ═══════════════════════════════════════════════════════════════
//  EVENTS
// ═══════════════════════════════════════════════════════════════

export async function getEvents(req, res) {
  try {
    const schoolId = schoolGuard(req);
    const { academicYearId, eventType, activityId, status, participationMode } = req.query;

    const cacheKey = await cacheService.buildKey(
      schoolId,
      `events:list:${academicYearId || "all"}:${eventType || "all"}:${activityId || "all"}:${status || "all"}:${participationMode || "all"}`
    );
    const cached = await cacheService.get(cacheKey);
    if (cached) return ok(res, { data: JSON.parse(cached) });

    const events = await prisma.activityEvent.findMany({
      where: {
        schoolId,
        isAutoGenerated: false,
        isArchived:      false,
        ...(academicYearId    ? { academicYearId }    : {}),
        ...(eventType         ? { eventType }         : {}),
        ...(activityId        ? { activityId }        : {}),
        ...(status            ? { status }            : {}),
        ...(participationMode ? { participationMode } : {}),
      },
      include: {
        activity:        { select: { id: true, name: true, participationType: true } },
        academicYear:    { select: { id: true, name: true } },
        eligibleClasses: {
          include: { classSection: { select: { id: true, grade: true, section: true, name: true } } },
        },
        _count: { select: { teams: true, participants: true, results: true } },
      },
      orderBy: [{ eventDate: "desc" }, { createdAt: "desc" }],
    });

    await cacheService.set(cacheKey, events);
    return ok(res, { data: events });
  } catch (e) {
    console.error("[getEvents]", e);
    return err(res, e.message, 500);
  }
}

export async function getEventById(req, res) {
  try {
    const schoolId = schoolGuard(req);

    const cacheKey = await cacheService.buildKey(schoolId, `events:${req.params.id}`);
    const cached = await cacheService.get(cacheKey);
    if (cached) return ok(res, { data: JSON.parse(cached) });

    const event = await prisma.activityEvent.findFirst({
      where: { id: req.params.id, schoolId, isArchived: false },
      include: {
        activity:        { select: { id: true, name: true, participationType: true } },
        academicYear:    { select: { id: true, name: true } },
        eligibleClasses: {
          include: { classSection: { select: { id: true, grade: true, section: true, name: true } } },
        },
        teams: {
          include: {
            members: { include: { student: { select: { id: true, name: true } } } },
          },
        },
        participants: { include: { student: { select: { id: true, name: true } } } },
        results: {
          include: {
            student: { select: { id: true, name: true } },
            team:    { select: { id: true, name: true } },
          },
        },
      },
    });

    if (!event) return err(res, "Event not found", 404);
    await cacheService.set(cacheKey, event);
    return ok(res, { data: event });
  } catch (e) {
    console.error("[getEventById]", e);
    return err(res, e.message, 500);
  }
}

export async function createEvent(req, res) {
  try {
    const schoolId    = schoolGuard(req);
    const createdById = req.user.id;
    const {
      name, description, activityId, eventType, participationMode,
      status = "DRAFT", eventDate, venue,
      maxTeamsPerClass, maxStudentsPerClass, academicYearId, classSectionIds = [],
    } = req.body;

    if (!name)              return err(res, "name is required");
    if (!eventType)         return err(res, "eventType is required");
    if (!participationMode) return err(res, "participationMode is required (INDIVIDUAL, TEAM, BOTH)");
    if (!academicYearId)    return err(res, "academicYearId is required");

    const validEventTypes         = ["COMPETITION", "CULTURAL", "PARTICIPATION", "CEREMONY"];
    const validParticipationModes = ["INDIVIDUAL", "TEAM", "BOTH"];
    const validStatuses           = ["DRAFT", "PUBLISHED", "COMPLETED", "CANCELLED"];

    if (!validEventTypes.includes(eventType))             return err(res, `eventType must be one of ${validEventTypes.join(", ")}`);
    if (!validParticipationModes.includes(participationMode)) return err(res, `participationMode must be one of ${validParticipationModes.join(", ")}`);
    if (!validStatuses.includes(status))                  return err(res, `status must be one of ${validStatuses.join(", ")}`);

    const ay = await prisma.academicYear.findFirst({ where: { id: academicYearId, schoolId } });
    if (!ay) return err(res, "Academic year not found");

    if (activityId) {
      const act = await prisma.activity.findFirst({ where: { id: activityId, schoolId, isArchived: false } });
      if (!act) return err(res, "Activity not found");
    }

    const event = await prisma.activityEvent.create({
      data: {
        name, description, activityId: activityId || null,
        eventType, participationMode, status,
        eventDate:           eventDate ? new Date(eventDate) : null,
        venue:               venue || null,
        maxTeamsPerClass:    maxTeamsPerClass    ? parseInt(maxTeamsPerClass)    : null,
        maxStudentsPerClass: maxStudentsPerClass ? parseInt(maxStudentsPerClass) : null,
        schoolId, academicYearId, createdById,
        eligibleClasses: { create: classSectionIds.map((csId) => ({ classSectionId: csId })) },
      },
      include: {
        activity:        { select: { id: true, name: true, participationType: true } },
        academicYear:    { select: { id: true, name: true } },
        eligibleClasses: {
          include: { classSection: { select: { id: true, grade: true, section: true, name: true } } },
        },
      },
    });

    await cacheService.invalidateSchool(schoolId);
    return ok(res, { data: event }, 201);
  } catch (e) {
    console.error("[createEvent]", e);
    return err(res, e.message, 500);
  }
}

export async function updateEvent(req, res) {
  try {
    const schoolId = schoolGuard(req);
    const existing = await prisma.activityEvent.findFirst({ where: { id: req.params.id, schoolId, isArchived: false } });
    if (!existing) return err(res, "Event not found", 404);

    const {
      name, description, activityId, eventType, participationMode,
      status, eventDate, venue, maxTeamsPerClass, maxStudentsPerClass, classSectionIds,
    } = req.body;

    const event = await prisma.$transaction(async (tx) => {
      if (Array.isArray(classSectionIds)) {
        await tx.eventClass.deleteMany({ where: { eventId: req.params.id } });
        await tx.eventClass.createMany({
          data: classSectionIds.map((csId) => ({ eventId: req.params.id, classSectionId: csId })),
        });
      }
      return tx.activityEvent.update({
        where: { id: req.params.id },
        data: {
          ...(name               !== undefined ? { name }               : {}),
          ...(description        !== undefined ? { description }        : {}),
          ...(eventType          !== undefined ? { eventType }          : {}),
          ...(participationMode  !== undefined ? { participationMode }  : {}),
          ...(status             !== undefined ? { status }             : {}),
          ...(venue              !== undefined ? { venue }              : {}),
          ...(activityId         !== undefined ? { activityId: activityId || null } : {}),
          ...(eventDate          !== undefined ? { eventDate: eventDate ? new Date(eventDate) : null } : {}),
          ...(maxTeamsPerClass    !== undefined ? { maxTeamsPerClass:    maxTeamsPerClass    ? parseInt(maxTeamsPerClass)    : null } : {}),
          ...(maxStudentsPerClass !== undefined ? { maxStudentsPerClass: maxStudentsPerClass ? parseInt(maxStudentsPerClass) : null } : {}),
        },
        include: {
          activity:        { select: { id: true, name: true, participationType: true } },
          academicYear:    { select: { id: true, name: true } },
          eligibleClasses: {
            include: { classSection: { select: { id: true, grade: true, section: true, name: true } } },
          },
        },
      });
    });

    await cacheService.invalidateSchool(schoolId);
    return ok(res, { data: event });
  } catch (e) {
    console.error("[updateEvent]", e);
    return err(res, e.message, 500);
  }
}

export async function deleteEvent(req, res) {
  try {
    const schoolId = schoolGuard(req);
    const existing = await prisma.activityEvent.findFirst({ where: { id: req.params.id, schoolId, isArchived: false } });
    if (!existing) return err(res, "Event not found", 404);

    await prisma.activityEvent.update({
      where: { id: req.params.id },
      data:  { isArchived: true },
    });

    await cacheService.invalidateSchool(schoolId);
    return ok(res, { message: "Event archived successfully" });
  } catch (e) {
    console.error("[deleteEvent]", e);
    return err(res, e.message, 500);
  }
}

// ═══════════════════════════════════════════════════════════════
//  HELPER ENDPOINTS — cached, invalidated with school
// ═══════════════════════════════════════════════════════════════

export async function getAcademicYears(req, res) {
  try {
    const schoolId = schoolGuard(req);

    const cacheKey = await cacheService.buildKey(schoolId, "academic-years");
    const cached = await cacheService.get(cacheKey);
    if (cached) return ok(res, { data: JSON.parse(cached) });

    const years = await prisma.academicYear.findMany({
      where:   { schoolId },
      select:  { id: true, name: true, isActive: true, startDate: true, endDate: true },
      orderBy: { startDate: "desc" },
    });

    await cacheService.set(cacheKey, years);
    return ok(res, { data: years });
  } catch (e) {
    return err(res, e.message, 500);
  }
}

export async function getClassSections(req, res) {
  try {
    const schoolId = schoolGuard(req);

    const cacheKey = await cacheService.buildKey(schoolId, "class-sections");
    const cached = await cacheService.get(cacheKey);
    if (cached) return ok(res, { data: JSON.parse(cached) });

    const sections = await prisma.classSection.findMany({
      where:   { schoolId },
      select:  { id: true, grade: true, section: true, name: true },
      orderBy: [{ grade: "asc" }, { section: "asc" }],
    });

    await cacheService.set(cacheKey, sections);
    return ok(res, { data: sections });
  } catch (e) {
    return err(res, e.message, 500);
  }
}